const fs = require('fs');
const path = require('path');
const phpPath = path.join(__dirname, 'payment_maintenance.php');
let lines = fs.readFileSync(phpPath, 'utf8').split(/\r?\n/);
const minimal = '    <script>window.currentCompanyId = <?php echo json_encode($session_company_id); ?>;</script>';
const scriptSrc = '    <script src="js/payment_maintenance.js?v=<?php echo time(); ?>"></script>';
const part1 = lines.slice(0, 138);
const part2 = [minimal, scriptSrc];
const part3 = lines.slice(1510);
const newContent = part1.concat(part2).concat(part3).join('\n');
fs.writeFileSync(phpPath, newContent, 'utf8');
console.log('Patched payment_maintenance.php');
