export const ACCOUNT_I18N = {
  en: {
    failedToLoadAccounts: "Failed to load accounts",
    networkError: "Network error",
    failedToSwitchCompany: "Failed to switch company",
    switchedTo: "Switched to {company}",
    toggleFailed: "Toggle failed",
    failedToLoadAccount: "Failed to load account",
    errorLoadingAccount: "Error loading account",
    deleteFailed: "Delete failed",
    accountsDeletedSuccessfully: "Accounts deleted successfully",
    paymentAlertRequiredFields: "When Payment Alert is enabled, both Alert Type and Start Date are required",
    saveFailed: "Save failed",
    accountSavedSuccessfully: "Account saved successfully",
    createFailed: "Create failed",
    loadLinksFailed: "Load links failed",
    currencySettingsSaved: "Currency settings saved",
    pleaseSelectCompanyFirst: "Please select a company first",
    pleaseSelectCurrencyFirst: "Please select a currency first (tap again to deselect)",
    failedOpenLinkModal: "Failed to open link account modal",
    accountLinksSavedSuccessfully: "Account links saved successfully",
    failedSaveAccountLinks: "Failed to save account links",
    accountList: "Account List",
    addAccount: "Add Account",
    searchByAccountOrName: "Search by Account or Name",
    inactive: "Inactive",
    showAll: "Show All",
    currencySetting: "Currency Setting",
    deleteWithCount: "Delete ({count})",
    groupId: "GroupID:",
    company: "Company:",
    groupAndCompany: "Group / Company",
    gcSelectGroup: "SELECT GROUP",
    gcSelectCompany: "SELECT COMPANY",
    gcConfirm: "Confirm",
    gcOneSelected: "1 selected",
    no: "No",
    account: "Account",
    name: "Name",
    role: "Role",
    alert: "Alert",
    status: "Status",
    lastLogin: "Last Login",
    remark: "Remark",
    action: "Action",
    loading: "Loading...",
    paginationOf: "{page} of {total}",
    edit: "Edit",
    linkAccountTitle: "Link Account",
    deleteConfirmMessage: "Are you sure you want to delete {count} selected account(s)?",
    confirmDelete: "Confirm Delete",
    actionCannotUndone: "This action cannot be undone.",
    cancel: "Cancel",
    delete: "Delete",
    editAccount: "Edit Account",
    personalInformation: "Personal Information",
    accountIdRequired: "Account ID *",
    nameRequired: "Name *",
    roleRequired: "Role *",
    selectRole: "Select Role",
    supplier: "SUPPLIER",
    passwordRequired: "Password *",
    payment: "Payment",
    paymentAlert: "Payment Alert",
    yes: "Yes",
    noWord: "No",
    alertType: "Alert Type",
    selectType: "Select Type",
    weekly: "Weekly",
    monthly: "Monthly",
    days: "{n} Days",
    startDate: "Start Date",
    alertAmount: "Alert (Amount)",
    enterAmountPlaceholder: "Enter amount (auto-converted to negative)",
    advancedAccount: "Advanced Account",
    otherCurrency: "Other Currency:",
    newCurrencyPlaceholder: "Enter new currency code (e.g., EUR, JPY, GBP)",
    createCurrency: "Create Currency",
    updateAccount: "Update Account",
    save: "Save",
    back: "Back",
    addCurrency: "Add Currency :",
    pleaseEnterNewCurrency: "Please enter new currency",
    add: "Add",
    currency: "Currency :",
    searchBar: "Search Bar",
    filterRow: "Filter Row",
    selectAll: "Select All",
    selectedCount: "{count} selected",
    bidirectional: "Bidirectional",
    unidirectional: "Unidirectional",
    bidirectionalDesc: "Bidirectional: Data syncs both ways.",
    unidirectionalDesc: "Unidirectional flows from A to B.",
    searchAccount: "Search account...",
    noAccountsToLink: "No accounts available to link.",
  },
  zh: {
    failedToLoadAccounts: "加载账号失败",
    networkError: "网络错误",
    failedToSwitchCompany: "切换公司失败",
    switchedTo: "已切换到 {company}",
    toggleFailed: "切换失败",
    failedToLoadAccount: "加载账号失败",
    errorLoadingAccount: "加载账号时发生错误",
    deleteFailed: "删除失败",
    accountsDeletedSuccessfully: "账号删除成功",
    paymentAlertRequiredFields: "启用 Payment Alert 时，Alert Type 和 Start Date 均为必填",
    saveFailed: "保存失败",
    accountSavedSuccessfully: "账号保存成功",
    createFailed: "创建失败",
    loadLinksFailed: "加载关联失败",
    currencySettingsSaved: "币种设置已保存",
    pleaseSelectCompanyFirst: "请先选择公司",
    pleaseSelectCurrencyFirst: "请先选择币种（再次点击可取消选中）",
    failedOpenLinkModal: "打开关联账号弹窗失败",
    accountLinksSavedSuccessfully: "账号关联保存成功",
    failedSaveAccountLinks: "保存账号关联失败",
    accountList: "账号列表",
    addAccount: "新增账号",
    searchByAccountOrName: "按账号或姓名搜索",
    inactive: "停用",
    showAll: "显示全部",
    currencySetting: "币种设置",
    deleteWithCount: "删除（{count}）",
    groupId: "GroupID：",
    company: "公司：",
    groupAndCompany: "集团 / 公司",
    gcSelectGroup: "选择集团",
    gcSelectCompany: "选择公司",
    gcConfirm: "确认",
    gcOneSelected: "已选 1",
    no: "序号",
    account: "账号",
    name: "姓名",
    role: "角色",
    alert: "提醒",
    status: "状态",
    lastLogin: "最后登录",
    remark: "备注",
    action: "操作",
    loading: "加载中...",
    paginationOf: "{page} / {total}",
    edit: "编辑",
    linkAccountTitle: "关联账号",
    deleteConfirmMessage: "确定删除已选中的 {count} 个账号吗？",
    confirmDelete: "确认删除",
    actionCannotUndone: "该操作无法撤销。",
    cancel: "取消",
    delete: "删除",
    editAccount: "编辑账号",
    personalInformation: "个人信息",
    accountIdRequired: "账号 ID *",
    nameRequired: "姓名 *",
    roleRequired: "角色 *",
    selectRole: "选择角色",
    supplier: "供应商",
    passwordRequired: "密码 *",
    payment: "支付",
    paymentAlert: "支付提醒",
    yes: "是",
    noWord: "否",
    alertType: "提醒类型",
    selectType: "选择类型",
    weekly: "每周",
    monthly: "每月",
    days: "{n} 天",
    startDate: "开始日期",
    alertAmount: "提醒金额",
    enterAmountPlaceholder: "输入金额（会自动转为负数）",
    advancedAccount: "高级账号",
    otherCurrency: "其他币种：",
    newCurrencyPlaceholder: "输入新币种代码（例如 EUR、JPY、GBP）",
    createCurrency: "创建币种",
    updateAccount: "更新账号",
    save: "保存",
    back: "返回",
    addCurrency: "新增币种：",
    pleaseEnterNewCurrency: "请输入新币种",
    add: "添加",
    currency: "币种：",
    searchBar: "搜索栏",
    filterRow: "筛选角色",
    selectAll: "全选",
    selectedCount: "已选 {count} 个",
    bidirectional: "双向",
    unidirectional: "单向",
    bidirectionalDesc: "双向：数据双向同步。",
    unidirectionalDesc: "单向：数据从 A 流向 B。",
    searchAccount: "搜索账号...",
    noAccountsToLink: "暂无可关联账号。",
  },
};

export function getAccountText(lang, key, params = {}) {
  const locale = lang === "zh" ? "zh" : "en";
  const template = ACCOUNT_I18N[locale][key] ?? ACCOUNT_I18N.en[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? ""));
}
