export const BANK_PROCESS_I18N = {
  en: {
    bankProcessList: "Bank Process List",
    accountingDue: "Accounting Due",
    addProcess: "Add Process",
    addAccount: "Add Account",
    selectDateRange: "Select date range",
    selectEndDate: "Select end date",
    clearDateRange: "Clear date range",
    search: "Search",
    showAll: "Show All",
    showInactive: "Show Inactive",
    showOfficial: "Show Official",
    showEInvoice: "Show E-Invoice",
    showBlock: "Show Block",
    delete: "Delete",
    groupId: "GroupID:",
    groupFilterAll: "ALL",
    currency: "Currency:",
    currencyDragHint: "Drag to reorder · Click to filter",
    company: "Company:",
    pageOf: "{current} of {total}",
    failedLoadBankProcesses: "Failed to load bank processes",
    switchCompanyFailed: "Switch company failed",
    addCountryFailed: "Add country failed",
    countryAdded: "Country added",
    addBankFailed: "Add bank failed",
    bankAdded: "Bank added",
    removeCountryFailed: "Remove country failed",
    countryRemoved: "Country removed",
    removeBankFailed: "Remove bank failed",
    bankRemoved: "Bank removed",
    removeCountryConfirm: "Remove country \"{country}\" and all its banks?",
    removeBankConfirm: "Remove bank \"{bank}\" from country \"{country}\"?",
    missingCompanyContext: "Missing company context.",
    failedLoadBankProcess: "Failed to load bank process",
    dayEndEarlierThanStart: "Day end cannot be earlier than Day start",
    saveFailed: "Save failed",
    bankProcessUpdated: "Bank process updated",
    bankProcessAdded: "Bank process added",
    needOneDueItem: "Please select at least one due item",
    transactionPostFailed: "Transaction post failed",
    postedToTransaction: "Posted to transaction",
    tickDeleteRows: "Please tick rows in Delete column",
    deleteDueFailed: "Delete from due failed",
    removedFromDue: "Removed from Accounting Due",
    remarkUpdateFailed: "Remark update failed",
    remarkUpdated: "Remark updated",
    resendFailed: "Resend failed",
    resendSuccessful: "Resend successful",
    deleteFailed: "Delete failed",
    statusUpdated: "Status updated",
    statusUpdateFailed: "Status update failed",
    processDeletedOne: "1 process deleted successfully",
    processDeletedMany: "{count} processes deleted successfully",
    accountAddedSuccessfully: "Account added successfully",
    pleaseSelectCompanyFirst: "Please select a company first",
    failedCreateCurrency: "Failed to create currency",
    currencyCreated: "Currency {code} created",
    failedDeleteCurrency: "Failed to delete currency",
    paymentAlertRequired: "When Payment Alert is Yes, Alert Type and Start Date are required.",
    alertAmountNegative: "Alert Amount must be negative.",

    no: "No",
    supplier: "Supplier",
    country: "Country",
    bank: "Bank",
    types: "Types",
    cardOwner: "Card Owner",
    contract: "Contract",
    insurance: "Insurance",
    customer: "Customer",
    cost: "Cost",
    price: "Price",
    profit: "Profit",
    status: "Status",
    date: "Date",
    action: "Action",
    selectAll: "Select all",
    selectAllDeletableOnPage: "Select all deletable bank processes on this page",
    loadData: "Load the Data...",
    noProcessDataFound: "No process data found",
    edit: "Edit",
    remark: "Remark",
    resend: "Resend",
    resendToAccountingDue: "Resend to Accounting Due",
    selectForDeletion: "Select for deletion",

    editProcess: "Edit Process",
    bankInformation: "Bank Information",
    detail: "Detail",
    countryCurrency: "Country (Currency)",
    selectCountry: "Select Country",
    addNewCountry: "Add New Country",
    selectBank: "Select Bank",
    addNewBank: "Add New Bank",
    buyPrice: "Buy Price",
    sellPrice: "Sell Price",
    enterAmount: "Enter amount",
    type: "Type",
    selectType: "Select Type",
    personal: "PERSONAL",
    enterprise: "ENTERPRISE",
    business: "BUSINESS",
    enterCardOwner: "Enter Card Owner",
    dayStart: "Day start",
    dayEnd: "Day end",
    companyAccount: "Company",
    autoCalculated: "Auto calculated",
    frequency: "Frequency",
    firstOfEveryMonth: "1st of Every Month",
    monthly: "Monthly",
    onceFrequency: "Once",
    dayEndNotUsedWhenOnce: "Not used when Frequency is Once",
    contractRequiredUnlessOnce: "Contract is required unless Frequency is Once.",
    selectedProfitSharing: "Selected Profit Sharing",
    noProfitSharingSelected: "No profit sharing selected",
    sop: "SOP",
    sopFilled: "SOP filled",
    remarkFilled: "Remark filled",
    updateProcess: "Update Process",
    cancel: "Cancel",

    selectOrAddCountry: "Select or Add Country",
    add: "Add",
    availableCountries: "Available Countries",
    searchCountries: "Search countries...",
    searchCountriesShort: "Search countries",
    newCountryNamePlaceholder: "Enter new country name...",
    removeCountryFromCompanyListAria: "Remove {country} from company country list",
    removeSelectedCountryAria: "Remove {country} from selection",
    selectedCountries: "Selected Countries",
    none: "None",
    selectExactlyOneCountry: "Please choose one country from the list on the left, or clear the selection and pick again.",
    confirm: "Confirm",

    selectOrAddBank: "Select or Add Bank",
    availableBanks: "Available Banks",
    searchBanks: "Search banks...",
    selectedBanks: "Selected Banks",
    selectExactlyOneBank: "Select exactly one bank on the right (add from the list or remove extras with ×).",

    addProfitSharing: "Add Profit Sharing",
    account: "Account",
    amount: "Amount",
    removeRow: "Remove row",
    addAnotherAccountAmount: "Add another Account & Amount",

    confirmDeleteTitle: "Confirm Delete",
    confirmDeleteMessage: "Are you sure you want to delete {count} process(es)? This action cannot be undone.",
    deleting: "Deleting...",

    selectAccount: "Select Account",
    searchAccount: "Search account...",

    resendToDueTitle: "Resend to Accounting Due",
    processLabel: "Process",
    billingSchedule: "Billing schedule",
    billingScheduleHint: "These values apply only to this Resend (which month to reopen). They are not saved to the process record; Edit Process keeps its own billing until you click Update Process.",
    resendAction: "Resend",

    notePlaceholder: "Enter notes for this process...",
    save: "Save",

    deleteCol: "Delete",
    selectAllForDelete: "Select all for delete",
    startDate: "Start Date",
    loading: "Loading...",
    noDueToday: "No process due for accounting today.",
    transaction: "Transaction",
  },
  zh: {
    bankProcessList: "银行流程列表",
    accountingDue: "待入账",
    addProcess: "新增流程",
    addAccount: "新增账号",
    selectDateRange: "选择日期范围",
    selectEndDate: "选择结束日期",
    clearDateRange: "清除日期范围",
    search: "搜索",
    showAll: "显示全部",
    showInactive: "显示停用",
    showOfficial: "显示官方",
    showEInvoice: "显示电子发票",
    showBlock: "显示封锁",
    delete: "删除",
    groupId: "GroupID：",
    groupFilterAll: "全部",
    currency: "币种：",
    currencyDragHint: "拖动调整顺序 · 点击筛选",
    company: "公司：",
    pageOf: "{current} / {total}",
    failedLoadBankProcesses: "加载银行流程失败",
    switchCompanyFailed: "切换公司失败",
    addCountryFailed: "新增国家失败",
    countryAdded: "国家已新增",
    addBankFailed: "新增银行失败",
    bankAdded: "银行已新增",
    removeCountryFailed: "删除国家失败",
    countryRemoved: "国家已删除",
    removeBankFailed: "删除银行失败",
    bankRemoved: "银行已删除",
    removeCountryConfirm: "删除国家“{country}”及其所有银行？",
    removeBankConfirm: "从国家“{country}”删除银行“{bank}”？",
    missingCompanyContext: "缺少公司上下文。",
    failedLoadBankProcess: "加载银行流程失败",
    dayEndEarlierThanStart: "结束日期不能早于开始日期",
    saveFailed: "保存失败",
    bankProcessUpdated: "银行流程已更新",
    bankProcessAdded: "银行流程已新增",
    needOneDueItem: "请至少选择一条待入账数据",
    transactionPostFailed: "入账失败",
    postedToTransaction: "已发送到交易",
    tickDeleteRows: "请勾选删除列中的行",
    deleteDueFailed: "从待入账删除失败",
    removedFromDue: "已从待入账移除",
    remarkUpdateFailed: "备注更新失败",
    remarkUpdated: "备注已更新",
    resendFailed: "重发失败",
    resendSuccessful: "重发成功",
    deleteFailed: "删除失败",
    statusUpdated: "状态已更新",
    statusUpdateFailed: "状态更新失败",
    processDeletedOne: "已成功删除 1 条流程",
    processDeletedMany: "已成功删除 {count} 条流程",
    accountAddedSuccessfully: "账号新增成功",
    pleaseSelectCompanyFirst: "请先选择公司",
    failedCreateCurrency: "创建币种失败",
    currencyCreated: "币种 {code} 已创建",
    failedDeleteCurrency: "删除币种失败",
    paymentAlertRequired: "当 Payment Alert 为 Yes 时，Alert Type 和 Start Date 为必填。",
    alertAmountNegative: "Alert Amount 必须为负数。",

    no: "序号",
    supplier: "供应商",
    country: "国家",
    bank: "银行",
    types: "类型",
    cardOwner: "卡主",
    contract: "合同",
    insurance: "保险",
    customer: "客户",
    cost: "成本",
    price: "售价",
    profit: "利润",
    status: "状态",
    date: "日期",
    action: "操作",
    selectAll: "全选",
    selectAllDeletableOnPage: "全选本页可删除银行流程",
    loadData: "加载数据中...",
    noProcessDataFound: "未找到流程数据",
    edit: "编辑",
    remark: "备注",
    resend: "重发",
    resendToAccountingDue: "重发到待入账",
    selectForDeletion: "勾选删除",

    editProcess: "编辑流程",
    bankInformation: "银行信息",
    detail: "详情",
    countryCurrency: "国家（币种）",
    selectCountry: "选择国家",
    addNewCountry: "新增国家",
    selectBank: "选择银行",
    addNewBank: "新增银行",
    buyPrice: "买价",
    sellPrice: "卖价",
    enterAmount: "输入金额",
    type: "类型",
    selectType: "选择类型",
    personal: "个人",
    enterprise: "企业",
    business: "商业",
    enterCardOwner: "输入卡主",
    dayStart: "起始日",
    dayEnd: "结束日",
    companyAccount: "公司",
    autoCalculated: "自动计算",
    frequency: "频率",
    firstOfEveryMonth: "每月1号",
    monthly: "按月",
    onceFrequency: "一次性",
    dayEndNotUsedWhenOnce: "Frequency 为「一次性」时不使用结束日",
    contractRequiredUnlessOnce: "除 Frequency 为「一次性」外，合同为必填。",
    selectedProfitSharing: "已选利润分成",
    noProfitSharingSelected: "未选择利润分成",
    sop: "SOP",
    sopFilled: "已填写 SOP",
    remarkFilled: "已填写备注",
    updateProcess: "更新流程",
    cancel: "取消",

    selectOrAddCountry: "选择或新增国家",
    add: "新增",
    availableCountries: "可用国家",
    searchCountries: "搜索国家...",
    searchCountriesShort: "搜索国家",
    newCountryNamePlaceholder: "输入新国家/币种代码...",
    removeCountryFromCompanyListAria: "从公司列表删除 {country}",
    removeSelectedCountryAria: "从已选中移除 {country}",
    selectedCountries: "已选国家",
    none: "无",
    selectExactlyOneCountry: "请从左侧列表选择一个国家；可点击右侧标签上的 × 清除后重选。",
    confirm: "确认",

    selectOrAddBank: "选择或新增银行",
    availableBanks: "可用银行",
    searchBanks: "搜索银行...",
    selectedBanks: "已选银行",
    selectExactlyOneBank: "请在右侧仅保留一个银行（可从左侧添加，或用 × 删除多余项）。",

    addProfitSharing: "新增利润分成",
    account: "账号",
    amount: "金额",
    removeRow: "删除行",
    addAnotherAccountAmount: "新增一行账号与金额",

    confirmDeleteTitle: "确认删除",
    confirmDeleteMessage: "确定删除 {count} 条流程吗？此操作不可撤销。",
    deleting: "删除中...",

    selectAccount: "选择账号",
    searchAccount: "搜索账号...",

    resendToDueTitle: "重发到待入账",
    processLabel: "流程",
    billingSchedule: "账单计划",
    billingScheduleHint: "这些值仅用于本次重发（决定重开月份），不会保存到流程记录；如需长期生效，请在 Edit Process 里点击 Update Process。",
    resendAction: "重发",

    notePlaceholder: "输入该流程备注...",
    save: "保存",

    deleteCol: "删除",
    selectAllForDelete: "全选删除",
    startDate: "开始日期",
    loading: "加载中...",
    noDueToday: "今天没有待入账流程。",
    transaction: "入账",
  },
};

export function getBankProcessText(lang, key, params = {}) {
  const locale = lang === "zh" ? "zh" : "en";
  const template = BANK_PROCESS_I18N[locale][key] ?? BANK_PROCESS_I18N.en[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? ""));
}
