export const RESET_PASSWORD_I18N = {
  en: {
    pageTitle: "Reset Password",
    companyPlaceholder: "Company / Group ID (or Owner Code)",
    emailPlaceholder: "Enter your email address",
    tacPlaceholder: "TAC",
    send: "SEND",
    sending: "Sending...",
    newPasswordPlaceholder: "New Password",
    confirmPasswordPlaceholder: "Confirm New Password",
    resetButton: "Reset Password",
    resetting: "Resetting...",
    backToLogin: "Back to Login",
    notice: "Notice",
    success: "Success",
    confirm: "Confirm",
    companyIdFirst: "Please enter Company ID first",
    emailFirst: "Please enter your email address first",
    tacSent: "TAC code has been sent to your email",
    verifyCodeLine: "Your verification code:",
    tacFailed: "Failed to send TAC. Please try again.",
    networkError: "Network error. Please try again.",
    passwordsNoMatch: "Passwords do not match",
    enterTac: "Please enter the TAC code",
    companyEmailRequired: "Company ID and email are required",
    resetSuccess: "Password reset successful! Redirecting to login...",
    resetFailed: "Failed to reset password. Please try again.",
    switchLang: "Switch language",
  },
  zh: {
    pageTitle: "重置密码",
    companyPlaceholder: "公司 / 集团 ID（或业主代码）",
    emailPlaceholder: "请输入邮箱地址",
    tacPlaceholder: "验证码（TAC）",
    send: "发送",
    sending: "发送中...",
    newPasswordPlaceholder: "新密码",
    confirmPasswordPlaceholder: "确认新密码",
    resetButton: "重置密码",
    resetting: "提交中...",
    backToLogin: "返回登录",
    notice: "提示",
    success: "成功",
    confirm: "确认",
    companyIdFirst: "请先填写公司 / 集团 ID",
    emailFirst: "请先填写邮箱地址",
    tacSent: "验证码已发送至您的邮箱",
    verifyCodeLine: "您的验证码：",
    tacFailed: "验证码发送失败，请稍后重试。",
    networkError: "网络异常，请稍后重试。",
    passwordsNoMatch: "两次输入的密码不一致",
    enterTac: "请填写验证码（TAC）",
    companyEmailRequired: "请填写公司 ID 与邮箱",
    resetSuccess: "密码重置成功！正在跳转登录页…",
    resetFailed: "密码重置失败，请稍后重试。",
    switchLang: "切换语言",
  },
}
