export const USER_LIST_I18N = {
  en: {
    failedToLoadUsers: "Failed to load users",
    couldNotSwitchCompany: "Could not switch company",
    companySwitchFailed: "Company switch failed",
    noPermissionCreateAccounts: "You do not have permission to create new accounts",
    onlyOwnerCanEditOwner: "Only the owner can edit owner records",
    loadUserFailed: "Load user failed",
    toggleFailed: "Toggle failed",
    statusUpdated: "Status updated",
    deletedUsersSuccess: "Successfully deleted {count} users!",
    deletionResult: "Deletion: {ok} succeeded, {fail} failed",
    passwordRequired: "Password is required",
    secondaryPasswordMustBe6Digits: "Secondary password must be 6 digits",
    saveFailed: "Save failed",
    saved: "Saved",
    userList: "User List",
    addUser: "Add User",
    searchPlaceholder: "Search Login ID,Name,Email",
    showInactive: "Show Inactive",
    inactive: "Inactive",
    showAll: "Show All",
    deleteWithCount: "Delete ({count})",
    deleteConfirmWithCount: "Are you sure you want to delete the following {count} user(s)?",
    groupId: "Group ID:",
    groupFilterAll: "ALL",
    company: "Company:",
    no: "No",
    loginId: "Login ID",
    name: "Name",
    email: "Email",
    role: "Role",
    status: "Status",
    lastLogin: "Last Login",
    createdBy: "Created By",
    action: "Action",
    selectAllDeletableAria: "Select all users that can be deleted",
    rowDeleteCheckboxAria: "Select user for deletion",
    loading: "Loading...",
    paginationOf: "{page} of {total}",
    editOwner: "Edit Owner",
    editUser: "Edit User",
    back: "Back",
    userInformation: "User Information",
    password: "Password",
    passwordRequiredMark: "Password *",
    secondaryPassword6Digits: "Secondary Password (6 digits)",
    secondaryPasswordPlaceholder: "Enter 6-digit password",
    nameRequired: "Name *",
    roleRequired: "Role *",
    selectRole: "Select Role",
    emailRequired: "Email *",
    companyRequired: "Company *",
    companyNoneSelected: "None selected",
    selectCompanies: "Choose companies",
    companySearchPlaceholder: "Filter by code…",
    companyPickerDone: "Done",
    companyPickerTitle: "Companies",
    permissions: "Permissions",
    permHome: "Home",
    permAdmin: "Admin",
    permOwnership: "Ownership",
    permReport: "Report",
    permMaintenance: "Maintenance",
    readOnly: "Read Only",
    dataCapture: "Data Capture",
    transactionPayment: "Transaction Payment",
    selectAll: "Select All",
    clearAll: "Clear All",
    account: "Account",
    process: "Process",
    save: "Save",
    cancel: "Cancel",
    confirmDelete: "Confirm Delete",
    delete: "Delete",
  },
  zh: {
    failedToLoadUsers: "加载用户失败",
    couldNotSwitchCompany: "无法切换公司",
    companySwitchFailed: "公司切换失败",
    noPermissionCreateAccounts: "您没有权限创建新账号",
    onlyOwnerCanEditOwner: "仅 Owner 可编辑 Owner 记录",
    loadUserFailed: "加载用户失败",
    toggleFailed: "切换状态失败",
    statusUpdated: "状态已更新",
    deletedUsersSuccess: "成功删除 {count} 位用户！",
    deletionResult: "删除结果：成功 {ok}，失败 {fail}",
    passwordRequired: "密码为必填项",
    secondaryPasswordMustBe6Digits: "二级密码必须为 6 位数字",
    saveFailed: "保存失败",
    saved: "保存成功",
    userList: "用户列表",
    addUser: "新增用户",
    searchPlaceholder: "搜索 登入账号/姓名/邮箱",
    showInactive: "显示停用",
    inactive: "停用",
    showAll: "显示全部",
    deleteWithCount: "删除（{count}）",
    deleteConfirmWithCount: "确认删除以下 {count} 位用户吗？",
    groupId: "集团：",
    groupFilterAll: "全部",
    company: "公司：",
    no: "序号",
    loginId: "登录 ID",
    name: "姓名",
    email: "邮箱",
    role: "角色",
    status: "状态",
    lastLogin: "最后登录",
    createdBy: "创建者",
    action: "操作",
    selectAllDeletableAria: "全选可删除的用户",
    rowDeleteCheckboxAria: "选择该用户以加入删除",
    loading: "加载中...",
    paginationOf: "{page} / {total}",
    editOwner: "编辑 Owner",
    editUser: "编辑用户",
    back: "返回",
    userInformation: "用户信息",
    password: "密码",
    passwordRequiredMark: "密码 *",
    secondaryPassword6Digits: "二级密码（6 位数字）",
    secondaryPasswordPlaceholder: "请输入 6 位密码",
    nameRequired: "姓名 *",
    roleRequired: "角色 *",
    selectRole: "选择角色",
    emailRequired: "邮箱 *",
    companyRequired: "公司 *",
    companyNoneSelected: "未选择",
    selectCompanies: "选择公司",
    companySearchPlaceholder: "按代码筛选…",
    companyPickerDone: "完成",
    companyPickerTitle: "公司",
    permissions: "权限",
    permHome: "首页",
    permAdmin: "管理",
    permOwnership: "股权",
    permReport: "报表",
    permMaintenance: "维护",
    readOnly: "只读",
    dataCapture: "数据采集",
    transactionPayment: "交易付款",
    selectAll: "全选",
    clearAll: "清空",
    account: "账号",
    process: "流程",
    save: "保存",
    cancel: "取消",
    confirmDelete: "确认删除",
    delete: "删除",
  },
};

export function getUserListText(lang, key, params = {}) {
  const locale = lang === "zh" ? "zh" : "en";
  const template = USER_LIST_I18N[locale][key] ?? USER_LIST_I18N.en[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? ""));
}
