export const transactionQueryKeys = {
  searchRoot: () => ["tx-search"],
  search: ({
    companyId,
    dateFrom,
    dateTo,
    showInactive,
    showCaptureOnly,
    hideZeroBalance,
    categories,
    currencyCodes,
  }) => [
    "tx-search",
    {
      companyId: Number(companyId ?? 0),
      dateFrom: String(dateFrom || ""),
      dateTo: String(dateTo || ""),
      showInactive: !!showInactive,
      showCaptureOnly: !!showCaptureOnly,
      hideZeroBalance: !!hideZeroBalance,
      categories: Array.isArray(categories) ? [...categories].sort() : [],
      currencyCodes: Array.isArray(currencyCodes) ? [...currencyCodes].sort() : [],
    },
  ],
  categories: () => ["tx-categories"],
  accounts: (companyId) => ["tx-accounts", Number(companyId ?? 0)],
  companyCurrencies: (companyId) => ["tx-company-currencies", Number(companyId ?? 0)],
  userCurrencyOrder: () => ["tx-user-currency-order"],
  history: ({ companyId, accountDbId, dateFrom, dateTo, currency, virtualCompanyCode }) => [
    "tx-history",
    Number(companyId ?? 0),
    String(accountDbId || ""),
    String(dateFrom || ""),
    String(dateTo || ""),
    String(currency || "").toUpperCase().trim(),
    String(virtualCompanyCode || "").toUpperCase().trim(),
  ],
  contraInbox: (companyId) => ["tx-contra-inbox", Number(companyId ?? 0)],
  contraInboxRoot: () => ["tx-contra-inbox"],
};
