import { interpolate } from "../shared/i18nHelpers.js";

const MONTH_LABELS_EN = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const MONTH_LABELS_ZH = ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"];
const WEEKDAYS_SHORT_EN = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const WEEKDAYS_SHORT_ZH = ["日", "一", "二", "三", "四", "五", "六"];

export const AUTO_RENEW_I18N = {
  en: {
    pageTitle: "Auto Renew",
    pageSubtitle: "Review and approve subscription renewals for companies expiring within 30 days.",
    company: "Company",
    expirationDate: "Expiration Date",
    timeRemaining: "Time Remaining",
    notSet: "Not set",
    noExpirationDate: "No expiration date",
    renewalPeriod: "Renewal Period",
    selectPeriod: "Select period",
    period7days: "7 days",
    period1month: "1 month",
    period3months: "3 months",
    period6months: "6 months",
    period1year: "1 year",
    loadFailed: "Failed to load: {message}",
    readOnlyNotice: "Only C168 Owner or Admin can approve or reject renewals.",
    accessDenied: "You do not have access to Auto Renew.",
    noResults: "No renewal requests match your search or filters.",
    emptyTitle: "All clear for now",
    emptyHintPending: "No companies are within the 30-day renewal window, or all requests have been processed.",
    emptyHintApproved: "No approved renewals in recent history.",
    emptyHintRejected: "No rejected renewals in recent history.",
    emptyHintAll: "Nothing in the renewal queue right now. Check back when a company nears expiration.",
    searchPlaceholder: "Search company, name or group…",
    filterGroupLabel: "Filters",
    filterPending: "Pending",
    filterApproved: "Approved",
    filterRejected: "Rejected",
    filterShowAll: "Show All",
    colNo: "No.",
    colCompany: "Company",
    colName: "Name",
    colPrice: "Price",
    colExpiration: "Expiration",
    colRemaining: "Remaining",
    colPeriod: "Period",
    colStatus: "Status",
    colFromAccount: "From Account",
    colToAccount: "To Account",
    colSubmitter: "Submitter",
    selectFromAccount: "Select payer",
    selectToAccount: "Select receiver",
    approve: "Approve",
    reject: "Reject",
    delete: "Delete",
    processing: "Processing…",
    confirmApprove: "Approve renewal for {company}? This will extend expiration and create a payment.",
    confirmReject: "Clear period and account selections for {company}?",
    confirmDelete: "Undo approval for {company}? This will delete the payment and revert expiration.",
    approvedSuccess: "Renewal approved",
    rejectedSuccess: "Selections cleared",
    deletedSuccess: "Approval undone",
    approveFailed: "Approve failed: {message}",
    rejectFailed: "Clear failed: {message}",
    deleteFailed: "Delete failed: {message}",
    noPriceHint: "Set Domain renewal price first",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    expExpired: "Expired",
    expToday: "Expires today",
    expDaysLeft: "{days} days left",
    prevPage: "Previous",
    nextPage: "Next",
    pageInfo: "Page {page} / {total} · {count} requests",
    renewBadgePending: "Renew",
    renewBadgeApproved: "Renewed",
    dateRange: "Processed date",
    historyDateRange: "Transaction date",
    selectDateRange: "Select date range",
    selectEndDate: "Select end date",
    clearDate: "Clear",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This week",
    lastWeek: "Last week",
    thisMonth: "This month",
    lastMonth: "Last month",
    thisYear: "This year",
    lastYear: "Last year",
    periodShortcutsAria: "Date presets",
    historyTitle: "Payment History",
    historyEmpty: "No auto-renew payments in this date range.",
    historyLoadFailed: "Failed to load payment history: {message}",
    histColDate: "Date",
    histColFrom: "From",
    histColTo: "To",
    histColAmount: "Amount",
    histColCurrency: "Currency",
    histColDescription: "Description",
    submitterPending: "—",
  },
  zh: {
    pageTitle: "自动续费审批",
    pageSubtitle: "审批 30 天内到期的客户公司续费申请。",
    company: "公司",
    expirationDate: "到期日",
    timeRemaining: "剩余时间",
    notSet: "未设置",
    noExpirationDate: "尚未设置到期日",
    renewalPeriod: "续费周期",
    selectPeriod: "选择周期",
    period7days: "7 天",
    period1month: "1 个月",
    period3months: "3 个月",
    period6months: "6 个月",
    period1year: "1 年",
    loadFailed: "加载失败：{message}",
    readOnlyNotice: "仅 C168 Owner 或 Admin 可审批续费。",
    accessDenied: "您无权访问自动续费。",
    noResults: "没有符合搜索或筛选条件的续费请求。",
    emptyTitle: "目前没有待处理项",
    emptyHintPending: "暂无进入 30 天续费窗口的公司，或相关请求已全部处理。",
    emptyHintApproved: "近期没有已批准的续费记录。",
    emptyHintRejected: "近期没有已拒绝的续费记录。",
    emptyHintAll: "续费队列为空。公司临近到期时会自动出现在此。",
    searchPlaceholder: "搜索公司、名称或集团…",
    filterGroupLabel: "筛选",
    filterPending: "待审批",
    filterApproved: "已批准",
    filterRejected: "已拒绝",
    filterShowAll: "全部",
    colNo: "序号",
    colCompany: "公司",
    colName: "名称",
    colPrice: "续费金额",
    colExpiration: "到期日",
    colRemaining: "剩余时间",
    colPeriod: "续费周期",
    colStatus: "状态",
    colFromAccount: "付款账户",
    colToAccount: "收款账户",
    colSubmitter: "提交人",
    selectFromAccount: "选择付款方",
    selectToAccount: "选择收款方",
    approve: "批准",
    reject: "拒绝",
    delete: "删除",
    processing: "处理中…",
    confirmApprove: "确认批准 {company} 的续费？将延长到期日并创建付款。",
    confirmReject: "确认清空 {company} 的周期与账户选择？",
    confirmDelete: "确认撤销 {company} 的批准？将删除付款并回退到期日。",
    approvedSuccess: "续费已批准",
    rejectedSuccess: "已清空选择",
    deletedSuccess: "已撤销批准",
    approveFailed: "批准失败：{message}",
    rejectFailed: "清空失败：{message}",
    deleteFailed: "删除失败：{message}",
    noPriceHint: "请先在 Domain 设置续费价格",
    statusPending: "待审批",
    statusApproved: "已批准",
    statusRejected: "已拒绝",
    expExpired: "已过期",
    expToday: "今日到期",
    expDaysLeft: "剩余 {days} 天",
    prevPage: "上一页",
    nextPage: "下一页",
    pageInfo: "第 {page} / {total} 页 · 共 {count} 条",
    renewBadgePending: "续费",
    renewBadgeApproved: "已续",
    dateRange: "处理日期",
    historyDateRange: "交易日期",
    selectDateRange: "选择日期范围",
    selectEndDate: "选择结束日期",
    clearDate: "清除",
    today: "今天",
    yesterday: "昨天",
    thisWeek: "本周",
    lastWeek: "上周",
    thisMonth: "本月",
    lastMonth: "上月",
    thisYear: "今年",
    lastYear: "去年",
    periodShortcutsAria: "日期快捷选项",
    historyTitle: "付款历史",
    historyEmpty: "该日期范围内没有自动续费付款。",
    historyLoadFailed: "加载付款历史失败：{message}",
    histColDate: "日期",
    histColFrom: "付款方",
    histColTo: "收款方",
    histColAmount: "金额",
    histColCurrency: "货币",
    histColDescription: "描述",
    submitterPending: "—",
  },
};

export function getAutoRenewText(lang, key, params = {}) {
  const locale = lang === "zh" ? "zh" : "en";
  const raw = AUTO_RENEW_I18N[locale]?.[key] ?? AUTO_RENEW_I18N.en[key] ?? key;
  return interpolate(raw, params);
}

export function getAutoRenewCalendarI18n(lang) {
  const locale = lang === "zh" ? "zh" : "en";
  const pack = AUTO_RENEW_I18N[locale] ?? AUTO_RENEW_I18N.en;
  return {
    dateRange: pack.dateRange,
    selectDateRange: pack.selectDateRange,
    selectEndDate: pack.selectEndDate,
    periodShortcutsAria: pack.periodShortcutsAria,
    monthLabels: locale === "zh" ? MONTH_LABELS_ZH : MONTH_LABELS_EN,
    weekdaysShort: locale === "zh" ? WEEKDAYS_SHORT_ZH : WEEKDAYS_SHORT_EN,
    today: pack.today,
    yesterday: pack.yesterday,
    thisWeek: pack.thisWeek,
    lastWeek: pack.lastWeek,
    thisMonth: pack.thisMonth,
    lastMonth: pack.lastMonth,
    thisYear: pack.thisYear,
    lastYear: pack.lastYear,
  };
}
