import { interpolate } from "../shared/i18nHelpers.js";

export const AUTO_RENEW_I18N = {
  en: {
    pageTitle: "Auto Renew",
    subscriptionInfo: "Subscription",
    autoRenewSettings: "Auto Renew Settings",
    company: "Company",
    expirationDate: "Expiration Date",
    timeRemaining: "Time Remaining",
    notSet: "Not set",
    noExpirationDate: "No expiration date",
    enableAutoRenew: "Enable Auto Renew",
    enableAutoRenewHint: "When enabled, your subscription will be extended by the selected period after the current expiration date (payment gateway coming soon).",
    renewalPeriod: "Renewal Period",
    selectPeriod: "Select period",
    period7days: "7 days",
    period1month: "1 month",
    period3months: "3 months",
    period6months: "6 months",
    period1year: "1 year",
    previewTitle: "Preview",
    previewExtend: "If enabled, expiration {from} will extend to {to}",
    previewNeedPeriod: "Select a renewal period to see preview",
    autoRenewOn: "Auto renew is ON",
    autoRenewOff: "Auto renew is OFF",
    save: "Save",
    saving: "Saving…",
    saved: "Auto renew settings saved",
    loadFailed: "Failed to load settings: {message}",
    saveFailed: "Failed to save: {message}",
    readOnlyNotice: "Only the company Owner can change auto renew settings.",
    noDateNotice: "Expiration date is not set. Please contact your administrator before enabling auto renew.",
    c168Notice: "Auto renew is not available for this company.",
    backDashboard: "Back to Dashboard",
    lastUpdated: "Last updated: {at} by {by}",
    expExpired: "Expired",
    expToday: "Expires today",
    expDaysLeft: "{days} days left",
    manageAutoRenew: "Manage auto renew",
  },
  zh: {
    pageTitle: "自动续费",
    subscriptionInfo: "订阅信息",
    autoRenewSettings: "自动续费设置",
    company: "公司",
    expirationDate: "当前到期日",
    timeRemaining: "剩余时间",
    notSet: "未设置",
    noExpirationDate: "尚未设置到期日",
    enableAutoRenew: "启用自动续费",
    enableAutoRenewHint: "开启后，将在当前到期日按所选周期自动延长订阅（支付网关功能稍后接入）。",
    renewalPeriod: "续费周期",
    selectPeriod: "选择周期",
    period7days: "7 天",
    period1month: "1 个月",
    period3months: "3 个月",
    period6months: "6 个月",
    period1year: "1 年",
    previewTitle: "预览",
    previewExtend: "若开启，到期日 {from} 将延长至 {to}",
    previewNeedPeriod: "请选择续费周期以查看预览",
    autoRenewOn: "自动续费已开启",
    autoRenewOff: "自动续费已关闭",
    save: "保存",
    saving: "保存中…",
    saved: "自动续费设置已保存",
    loadFailed: "加载失败：{message}",
    saveFailed: "保存失败：{message}",
    readOnlyNotice: "仅公司 Owner 可修改自动续费设置。",
    noDateNotice: "尚未设置到期日，请联系管理员后再开启自动续费。",
    c168Notice: "当前公司不支持自动续费。",
    backDashboard: "返回 Dashboard",
    lastUpdated: "最后更新：{at}，操作人 {by}",
    expExpired: "已过期",
    expToday: "今日到期",
    expDaysLeft: "剩余 {days} 天",
    manageAutoRenew: "管理自动续费",
  },
};

export function getAutoRenewText(lang, key, params = {}) {
  const locale = lang === "zh" ? "zh" : "en";
  const raw = AUTO_RENEW_I18N[locale]?.[key] ?? AUTO_RENEW_I18N.en[key] ?? key;
  return interpolate(raw, params);
}
