import { interpolate } from "../shared/i18nHelpers.js";

export const AUTO_RENEW_I18N = {
  en: {
    pageTitle: "Auto Renew",
    company: "Company",
    expirationDate: "Expiration Date",
    timeRemaining: "Time Remaining",
    notSet: "Not set",
    noExpirationDate: "No expiration date",
    renewalPeriod: "Renewal Period",
    selectPeriod: "Select period",
    period7days: "7 days",
    period1month: "1 month",
    period3months: "3 months",
    period6months: "6 months",
    period1year: "1 year",
    loadFailed: "Failed to load: {message}",
    readOnlyNotice: "Only C168 Owner or Admin can approve or reject renewals.",
    accessDenied: "You do not have access to Auto Renew.",
    noResults: "No renewal requests match your search or filters.",
    searchPlaceholder: "Search company, name or group…",
    filterGroupLabel: "Filters",
    filterPending: "Pending",
    filterApproved: "Approved",
    filterRejected: "Rejected",
    filterShowAll: "Show All",
    colNo: "No.",
    colCompany: "Company",
    colName: "Name",
    colPrice: "Price",
    colExpiration: "Expiration",
    colRemaining: "Remaining",
    colPeriod: "Period",
    colStatus: "Status",
    colFromAccount: "From Account",
    colToAccount: "To Account",
    selectFromAccount: "Select payer",
    selectToAccount: "Select receiver",
    approve: "Approve",
    reject: "Reject",
    processing: "Processing…",
    confirmApprove: "Approve renewal for {company}? This will extend expiration and create a payment.",
    confirmReject: "Reject renewal for {company}?",
    approvedSuccess: "Renewal approved",
    rejectedSuccess: "Renewal rejected",
    approveFailed: "Approve failed: {message}",
    rejectFailed: "Reject failed: {message}",
    noPriceHint: "Set Domain renewal price first",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    expExpired: "Expired",
    expToday: "Expires today",
    expDaysLeft: "{days} days left",
    prevPage: "Previous",
    nextPage: "Next",
    pageInfo: "Page {page} / {total} · {count} requests",
    renewBadgePending: "Renew",
    renewBadgeApproved: "Renewed",
  },
  zh: {
    pageTitle: "自动续费审批",
    company: "公司",
    expirationDate: "到期日",
    timeRemaining: "剩余时间",
    notSet: "未设置",
    noExpirationDate: "尚未设置到期日",
    renewalPeriod: "续费周期",
    selectPeriod: "选择周期",
    period7days: "7 天",
    period1month: "1 个月",
    period3months: "3 个月",
    period6months: "6 个月",
    period1year: "1 年",
    loadFailed: "加载失败：{message}",
    readOnlyNotice: "仅 C168 Owner 或 Admin 可审批续费。",
    accessDenied: "您无权访问自动续费。",
    noResults: "没有符合搜索或筛选条件的续费请求。",
    searchPlaceholder: "搜索公司、名称或集团…",
    filterGroupLabel: "筛选",
    filterPending: "待审批",
    filterApproved: "已批准",
    filterRejected: "已拒绝",
    filterShowAll: "全部",
    colNo: "序号",
    colCompany: "公司",
    colName: "名称",
    colPrice: "续费金额",
    colExpiration: "到期日",
    colRemaining: "剩余时间",
    colPeriod: "续费周期",
    colStatus: "状态",
    colFromAccount: "付款账户",
    colToAccount: "收款账户",
    selectFromAccount: "选择付款方",
    selectToAccount: "选择收款方",
    approve: "批准",
    reject: "拒绝",
    processing: "处理中…",
    confirmApprove: "确认批准 {company} 的续费？将延长到期日并创建付款。",
    confirmReject: "确认拒绝 {company} 的续费？",
    approvedSuccess: "续费已批准",
    rejectedSuccess: "续费已拒绝",
    approveFailed: "批准失败：{message}",
    rejectFailed: "拒绝失败：{message}",
    noPriceHint: "请先在 Domain 设置续费价格",
    statusPending: "待审批",
    statusApproved: "已批准",
    statusRejected: "已拒绝",
    expExpired: "已过期",
    expToday: "今日到期",
    expDaysLeft: "剩余 {days} 天",
    prevPage: "上一页",
    nextPage: "下一页",
    pageInfo: "第 {page} / {total} 页 · 共 {count} 条",
    renewBadgePending: "续费",
    renewBadgeApproved: "已续",
  },
};

export function getAutoRenewText(lang, key, params = {}) {
  const locale = lang === "zh" ? "zh" : "en";
  const raw = AUTO_RENEW_I18N[locale]?.[key] ?? AUTO_RENEW_I18N.en[key] ?? key;
  return interpolate(raw, params);
}
