/** Auto-generated by scripts/sync-datacapture-legacy-version.mjs — do not edit. */
/** Content hash of js/datacapture.js (updates when you run npm run build / dev). */
export const DATA_CAPTURE_LEGACY_ASSET_VERSION = "869bb6bf5346";
export const DATA_CAPTURE_LEGACY_SCRIPT_PATH = "js/datacapture.js?v=869bb6bf5346";
export const DATA_CAPTURE_LEGACY_ASSET_MTIME = "2026-05-19T02:48:56.805Z";
