/** Auto-generated by scripts/sync-datacapture-legacy-version.mjs — do not edit. */
/** Content hash of js/datacapture.js (updates when you run npm run build / dev). */
export const DATA_CAPTURE_LEGACY_ASSET_VERSION = "0b380cc8577b";
export const DATA_CAPTURE_LEGACY_SCRIPT_PATH = "js/datacapture.js?v=0b380cc8577b";
export const DATA_CAPTURE_LEGACY_ASSET_MTIME = "2026-05-19T02:54:32.387Z";
