/** Auto-generated by scripts/sync-datacapture-legacy-version.mjs — do not edit. */
/** Content hash of js/datacapture.js (updates when you run npm run build / dev). */
export const DATA_CAPTURE_LEGACY_ASSET_VERSION = "5c475b0bc867";
export const DATA_CAPTURE_LEGACY_SCRIPT_PATH = "js/datacapture.js?v=5c475b0bc867";
export const DATA_CAPTURE_LEGACY_ASSET_MTIME = "2026-05-19T03:03:08.732Z";
